name: Unit Test

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Test
    env:
      NODE_OPTIONS: --max-old-space-size=6144
    steps:
      - uses: actions/checkout@v4
      - name: Cache Nx
        uses: actions/cache@v4
        with:
          path: |
            .moon/cache/hashes
            .moon/cache/outputs
          key: cache-moon-${{ github.sha }}
          restore-keys: |
            cache-moon-
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: yarn
      - uses: moonrepo/setup-toolchain@v0
      - run: moon ci karbon:build
      - run: yarn test
