name: Unit Test

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Test
    env:
      NODE_OPTIONS: --max-old-space-size=6144
    steps:
      - uses: actions/checkout@v3
      - name: Cache Nx
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/nx
          key: cache-nx-${{ hashFiles('yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            cache-nx-${{ hashFiles('yarn.lock') }}-
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
      - run: yarn install --inline-builds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn build
      - run: yarn test
